### ISSUE TITLE
cant loggin in the webinterface of cupid

### ISSUE THREAD

**Issue by ChrSchultz** [iinnovations/cupidweblib#1]
always if i try to log in by clicking on the login button, the appears a error-page with the message:
Page auth/login not found on this server. 
I tried to alter the urls into auth/login.php and auth/loginmobile.php and all the other required urls... then the login-form appears, but after the login nothing happens.
Thanks
Christoph Schultz
Url to my Pi's cupid... https://raspistuetensen.ddns.net:56235/

I forked the Repository and created a new branche with my workarounds, maby not perfect workarounds.
https://github.com/ChrSchultz/cupidweblib/tree/workarounds

**Comment by iinnovations** [comment]
Hi Christoph,

Check your server configuration. You'll need URL rewrite enabled and a site config like this (for nginx): 

https://github.com/iinnovations/iicontrollibs/blob/master/misc/nginx/nginxsite

There's a config in there for apache, but I have to admit I have not used it in some time. 

You can test they are readable by navigating to the full urls, e.g.

<<ipaddress>>/auth/login.php

Sounds like this is working fine. 

As heads up, update coming soon with total update of database module with class-based approach.

**Comment by ChrSchultz** [comment]
Thanks for the help, I added in the the default-ssl.conf the line
RewriteEnine on for /var/www/
and the nginx rewrite line and replaced rewrite with RewriteRule and last with [L], and like this.
RewriteRule ^/auth/login$ auth/login.php [L] ...
than I restarted apache2 but nothing happens...

**Comment by iinnovations** [comment]
Do you still get 404? Or is the url found but nothing else happens?

If 404, your rewrite is still incorrect. If found but nothing happens, 
check apache log, mostly likely at /var/log/apache2/error.log. There are 
many possibilities here -- did you create your auths database? Is it 
referenced by location correctly in user.php? These are good places to 
start.

**Comment by ChrSchultz** [comment]
now it works, but if i tried to sign up, but if i click on sign up-button a empty page appears and nothing will happen... How can I create the auths database?
the apache 2 error.log:
[Sun Jan 15 00:49:17.702204 2017] [:error] [pid 17049] [client 192.168.178.23:60317] PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in /var/www/auth/user.php:276\nStack trace:\n#0 /var/www/auth/user.php(276): PDO->__construct('sqlite:/var/www...')\n#1 /var/www/auth/user.php(136): user->sqlite()\n#2 /var/www/auth/user.php(93): user->signup()\n#3 /var/www/auth/user.php(735): user->__construct()\n#4 /var/www/auth/signup.php(1): require_once('/var/www/auth/u...')\n#5 {main}\n  thrown in /var/www/auth/user.php on line 276, referer: https://192.168.178.19:56235/auth/signup
I found the error: missing php5-sqlite module.. but after i had installed the module i tried to sign up and got  an error-msg: on signing up:  somthing went wrong... but no error is logged to the httpds error.log...

**Comment by CuPIDcontrols** [comment]
These databases are built using the rebuilddatabases.py in 
iicontrollibs. I'm currently testing an uprev that uses the new dblib on 
a few builds and will push it shortly.

**Comment by ChrSchultz** [comment]
Now I am able to log in. but the mobile/index.html shows always:
Not logged in 
logged_in()) ?> logged_in()) ?>
...
https://raspistuetensen.ddns.net:56235/

**Comment by CuPIDcontrols** [comment]
You need to enable interpretation of php in HTML files. There's a line for that in the site config I mentioned.

**Comment by ChrSchultz** [comment]
right, that was the mistake.
summary: 
1. added RewriteRules for apache2 in default-ssl.conf file
2. install php5-sqlite
3. added "AddType application/x-httpd-php .php .html for /var/www or (path to cupidweblib) in default-ssl.conf file.
4. set permissions for the databases of cupidlife readable for www-data user and group. and ownership to www-data:www-data. 
than all will work fine. 
Thanks!

**Comment by iinnovations** [comment]
Christoph,

Thanks for the update.

For what it's worth, these steps are all in the initscript in 
iicontrollibs/misc/initscript.sh

Colin
